/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ceron_alex (https://sketchfab.com/ceron_alex)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mercedes-benz-cls53-amg-2022-a1fec16bcc9d4d3c89ac0da2bb048a8b
Title: Mercedes-Benz CLS53 AMG 2022
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

function CLA45(props) {
  const { nodes, materials } = useGLTF("/models/CLA45.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.3}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={2.9}>
            <group rotation={[Math.PI / 2, 0, 0]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Rear_Lights_Panel_red_0.geometry}
                material={materials.material}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Rear_Lights_Panel_red_0_1.geometry}
                material={materials.material}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Left_Valve_black_0.geometry}
              material={materials.black}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Left_Brake_D1_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Rignt_Brake_D1_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Left_Brake_red_d_0.geometry}
              material={materials.red_d}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Left_Tire_tire_mat5_0.geometry}
              material={materials.tire_mat5}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Right_Tire_tire_mat5_0.geometry}
              material={materials.tire_mat5}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Plates_plate_0.geometry}
              material={materials.plate}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Left_Brake_Disk_brakes2_0.geometry}
              material={materials.brakes2}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Right_Brake_Disk_brakes2_0.geometry}
              material={materials.brakes2}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_logo_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Light_Glass_In_r_glass_0.geometry}
              material={materials.r_glass}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Exhaust_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.R_Lights_Glass_glass_0.geometry}
              material={materials.glass}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Blickers_red_0.geometry}
              material={materials.material}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.R_Lights_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.R_Light_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Exhaust_Detail_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Brake_Lights_r_lights_0.geometry}
              material={materials.r_lights}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.P_Indicators_Rear_body_0.geometry}
              material={materials.body}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Lights_Back_black_shiny_0.geometry}
              material={materials.black_shiny}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Light_Glass_Out_r_glass_0.geometry}
              material={materials.r_glass}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Bumper_Diffuse_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Trunk_Lid_body_0.geometry}
              material={materials.body}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Right_Valve_black_0.geometry}
              material={materials.black}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Right_Brake_red_d_0.geometry}
              material={materials.red_d}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Left_Brake_D2_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Right_Brake_D2_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Right_Wheel_Drive_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Left_Wheel_Drive_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Left_Disk_RIM_black_0.geometry}
              material={materials.black}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Right_Brake_Disk_Balancyrs_black_0.geometry}
              material={materials.black}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Left_Brake_Disk_Balancyrs_black_0.geometry}
              material={materials.black}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Bumper_D_black001_0.geometry}
              material={materials["black.001"]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Shilds_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Right_Wheel_Logo_Back_black_shiny_0.geometry}
              material={materials.black_shiny}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Left_Wheel_Logo_Back_black_shiny_0.geometry}
              material={materials.black_shiny}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Left_Wheel_Logo_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Right_Wheel_Logo_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Left_Disk_Detail_black_0.geometry}
              material={materials.black}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Right_Disk_Detail_black_0.geometry}
              material={materials.black}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Left_Wheel_Pintle_black_shiny_0.geometry}
              material={materials.black_shiny}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Right_Wheel_Pintle_black_shiny_0.geometry}
              material={materials.black_shiny}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Bridge_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Door_Handles_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Interrior_Details_black001_0.geometry}
              material={materials["black.001"]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Body_Glasses_d_glass_0.geometry}
              material={materials.d_glass}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Door_D1_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Door_D2_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Left_Tire_tire_mat5_0.geometry}
              material={materials.tire_mat5}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Right_Tire_tire_mat5_0.geometry}
              material={materials.tire_mat5}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Left_Brake_Disk_brakes2_0.geometry}
              material={materials.brakes2}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Plates_plate_0.geometry}
              material={materials.plate}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Right_Brake_Disk_brakes2_0.geometry}
              material={materials.brakes2}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Body_Details_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Interrior_Logo_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Steering_Wheel_black_0.geometry}
              material={materials.black}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Mirrors_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Mirrors_Indicators_Back_d_glass_0.geometry}
              material={materials.d_glass}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Mirrors_Indicators_Light_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Windscreen_Wiper_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Left_Shild_AMG_Back_black_shiny_0.geometry}
              material={materials.black_shiny}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Right_Shild_AMG_Back_black_shiny_0.geometry}
              material={materials.black_shiny}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Right_Shild_AMG_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Left_Shild_AMG_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Right_Shild_AMG_Frame_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Left_Shild_AMG_Frame_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Left_Shild_Turbo_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Right_Shild_Turbo_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Hood_Panel_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Right_Brake_D1_red_d_0.geometry}
              material={materials.red_d}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Left_Brake_D1_red_d_0.geometry}
              material={materials.red_d}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Right_Brake_red_d_0.geometry}
              material={materials.red_d}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Left_Brake_red_d_0.geometry}
              material={materials.red_d}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Right_Brake_D2_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Right_Brake_D_red_d_0.geometry}
              material={materials.red_d}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Right_Brake_AMG_black_shiny_0.geometry}
              material={materials.black_shiny}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Left_Brake_D2_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Left_Brake_D_red_d_0.geometry}
              material={materials.red_d}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Left_Brake_AMG_black_shiny_0.geometry}
              material={materials.black_shiny}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Right_Wheel_Drive_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Left_Wheel_Drive_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Right_Wheel_Pintle_black_shiny_0.geometry}
              material={materials.black_shiny}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Left_Wheel_Pintle_black_shiny_0.geometry}
              material={materials.black_shiny}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes.Rear_Right_Brake_Disk_Balancyrs001_black_0.geometry
              }
              material={materials.black}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Left_Wheel_Logo_Back_black_shiny_0.geometry}
              material={materials.black_shiny}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes.Front_Right_Wheel_Logo_Back_black_shiny_0.geometry
              }
              material={materials.black_shiny}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Hatchway_vd_glass_0.geometry}
              material={materials.vd_glass}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Body_Bottom_black001_0.geometry}
              material={materials["black.001"]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Left_Brake_Disk_Balancyrs_black_0.geometry}
              material={materials.black}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Left_Disk_Detail_black_0.geometry}
              material={materials.black}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Left_Wheel_Logo_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Right_Wheel_Logo_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Right_Disk_Detail_black_0.geometry}
              material={materials.black}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Right_Valve_black_0.geometry}
              material={materials.black}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Left_Valve_black_0.geometry}
              material={materials.black}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Lights_Back_black_shiny_0.geometry}
              material={materials.black_shiny}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Optics_Details_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_LIght_Glass_glass_0.geometry}
              material={materials.glass}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Lights_HighBeam_lights_0.geometry}
              material={materials.lights}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Light_LowBeam_lights_0.geometry}
              material={materials.lights}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Light_Chrome_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Light_Glass_LowBeam_glass_0.geometry}
              material={materials.glass}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Bumper_D2_black_shiny_0.geometry}
              material={materials.black_shiny}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Bumper_D1_black_shiny_0.geometry}
              material={materials.black_shiny}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Diffusor_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Lights_D_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Bumper_D3_body_0.geometry}
              material={materials.body}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cooler_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cooler_D_black001_0.geometry}
              material={materials["black.001"]}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Splitter_D_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.P_Indicators_Front_black_shiny_0.geometry}
              material={materials.black_shiny}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Splitter_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Grill_D_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.P_Indicators_Grill_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Logo_D2_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Grill_Frame_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Grill_AMG_D_black_shiny_0.geometry}
              material={materials.black_shiny}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Hood_Logo_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Hood_Logo_D_black_shiny_0.geometry}
              material={materials.black_shiny}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Grill_AMG001_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Grill_D1_black_shiny_0.geometry}
              material={materials.black_shiny}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Logo_D1_black_shiny_0.geometry}
              material={materials.black_shiny}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Grill_Camera_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Grill_D2_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Grill_Logo_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Hatchway_Detail_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Grill_Chrome_chrome_0.geometry}
              material={materials.chrome}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Left_Disk_black_0.geometry}
              material={materials.black}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Left_Disk_black_0.geometry}
              material={materials.black}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Body_D1_body_0.geometry}
              material={materials.body}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Right_Disk_black_0.geometry}
              material={materials.black}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Interrior_interior_0.geometry}
              material={materials.interior}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Diffusor_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Bumper_body_0.geometry}
              material={materials.body}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Body_D2_body_0.geometry}
              material={materials.body}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Bumper_body_0.geometry}
              material={materials.body}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Body_D3_black_shiny_0.geometry}
              material={materials.black_shiny}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Front_Right_Disk_black_0.geometry}
              material={materials.black}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rear_Left_Lights_red_0.geometry}
              material={materials.material}
              rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Grill_AMG_black_matt_0.geometry}
              material={materials.black_matt}
              rotation={[Math.PI / 2, 0, 0]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

export default CLA45;

useGLTF.preload("/models/CLA45.glb");
